In [8]:
import numpy as np



In [12]:
arr= np.array([1,2,3,4])

In [25]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((4,4), 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [21]:
np.eye(5)  #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.linspace(1,100,5)  ##divides array into 5 elements with equal target

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [28]:
myarr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
myarr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
myarr.shape  # rows and coloums(4,3)
myarr.size  #total number of  elements
myarr.ndim   ##dimension 2D
myarr.dtype  ##storage type  int  32 or 64

dtype('int32')

##CHANGING DATATYPES


In [35]:
n=myarr.astype('float64')

n.dtype

dtype('float64')

In [37]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
reshaped= arr.reshape((2,6))
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [50]:
##flatten--> convert to 1D
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])