In [3]:
import numpy as np

arr= np.array([[1,2,3],[2,4,5], [6,7,8]])
arr

array([[1, 2, 3],
       [2, 4, 5],
       [6, 7, 8]])

In [29]:
arr= arr.astype('float64')

In [30]:
arr.dtype

dtype('float64')

In [33]:
myarr= np.array([1,2,3,4,5,6,7,8,9])


In [38]:
myarr[myarr%2==0]

array([[1, 2, 3],
       [7, 8, 9]])

In [35]:
myarr= myarr.reshape((3,3))
myarr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr= np.array([1,2,3,4,50,60,70,80,90])


In [51]:
arr[arr>=50]


array([50, 60, 70, 80, 90])