In [1]:
import numpy as np


arr= np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

flat = arr.flatten()

flat

In [7]:
flat[0:6], flat[1], flat[9]

(array([1, 2, 3, 4, 5, 6]), 2, 10)

In [9]:
flat[:5], flat[3:]

(array([1, 2, 3, 4, 5]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [13]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

Slicing returns a view, not a copy! Changes affect the original array...BELOW IS EXAMPLE

In [16]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
b= flat[3:7]
b

array([4, 5, 6, 7])

In [19]:
b[1] = 7777
b

array([   4, 7777,    6,    7])

In [22]:
flat
###CHANGES APPPEAR HERE AS WELL

array([   1,    2,    3,    4, 7777,    6,    7,    8,    9,   10,   11,
         12])

In [23]:
##copyyyy

c= flat.copy()
c


array([   1,    2,    3,    4, 7777,    6,    7,    8,    9,   10,   11,
         12])

In [26]:
c[0]=99999
c
flat

array([   1,    2,    3,    4, 7777,    6,    7,    8,    9,   10,   11,
         12])

fancy indexing and boolean masking

In [28]:
arr= np.array([1,43,5,6,334,35])


In [29]:
arr[[1,2,5]]

array([43,  5, 35])

In [32]:
##boolean masking


arr[arr>30]

array([ 43, 334,  35])