In [2]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr[0]   ##indexing of array
arr[1]

array([1, 2, 3])

In [10]:
axis=0  ##crossponds to rows
axis= 1 ##crossponds to columns

In [11]:
np.sum(arr, axis=0)   #rows sum
np.sum(arr, axis=1)    ##column sum


array([ 6, 15, 24])

In [12]:
arr[0][1]   ##python way to get the a12th element 

2

In [14]:
arr[0,1]  #numpy way

2

In [19]:
arr[0:2, 1:3]    ##0:2 rows ,  1:3 columns

array([[2, 3],
       [5, 6]])

In [ ]:
arr3D = np.array([
    [
    [1, 2, 3],       ##first 2d array
    [4, 5, 6]
    ],
    
     [
    [7, 8, 9],
    [10, 11, 12]
     ]     ##second 2d array


])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 