In [11]:
# ##USING PYTHON LISTS


import time
size= 100000



l1= list(range(size))

l2= list(range(size))     

start= time.time()

add= [x+y for x,y in zip(l1,l2)]
end=time.time()
print(add[0:10])


print(end-start)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.007004499435424805


In [9]:

##USING Numpy arrays

import numpy as np

size= 100000



l1= np.array(range(size))
l2= np.array(range(size))



start= time.time()

add= l1+l2
end=time.time()

print(add[0:10])


print(end-start)





[ 0  2  4  6  8 10 12 14 16 18]
0.0010046958923339844


In [15]:
np.array([1,2,3,4,5,])

array([1, 2, 3, 4, 5])

In [21]:
arr= np.array([[1,2,4] ,[4,5,8]])

In [26]:
type(arr)
arr.shape

(2, 3)

In [38]:
##normalpython loop
li=[1,2,3,4,5]
sq_li= [x**2 for x in li]
print(sq_li)


##numpy vectorized operation
arr1 = np.array([1,2,3,4,5,10])
numpy_squares= arr1**2
print(numpy_squares)


[1, 4, 9, 16, 25]
[  1   4   9  16  25 100]
